### ISSUE TITLE
My staked ETH in puffer is drained yesterday my drainer

### ISSUE THREAD

**Issue by sairama22** [slowmist/Knowledge-Base#25]
My staked puffer Eth was drained by drainer so why   puffer profile still giving me the eigne points even though my Puffer ether was drained which means my puffereth who ever drained he has staked it 
is their any way this can be tracked and sent it back to my wallet
![phishing](https://github.com/slowmist/Knowledge-Base/assets/86326728/82eefa42-c3cd-4675-bfbb-ebbe931cb62f)

This is a big issue regarding points, even though my puffer eth is not in my wallet still i am getting Eigen Layer points
transaction ID
0x50eefd01e0903f52b1c6ff587d768dd335ff6b70f86397defdbbfd18539eb888

**Comment by cyousenmei** [comment]
这是来自QQ邮箱的自动回复邮件。原因邮箱的主人还没回家(・∀・)

**Comment by sairama22** [comment]
> 这是来自QQ邮箱的自动回复邮件。原因邮箱的主人还没回家(・∀・)

what is this is this chinese???
