### ISSUE TITLE
points 

### ISSUE THREAD

**Issue by yemahn09** [slowmist/Knowledge-Base#26]
i was doing social avicitives but do not increase any point

**Comment by yemahn09** [comment]
![image](https://github.com/slowmist/Knowledge-Base/assets/163313445/cda3fe87-89db-400e-a23d-459329bf2936)

**Comment by yemahn09** [comment]
my twitter username is 
@ye_plena

**Comment by William23743** [comment]
why can't my sender application wallet connect to the sender browser?

My Twitter name is @william23743

**Comment by William23743** [comment]
why can't my sender application wallet connect to the sender browser

My Twitter name is @william23743
![Screenshot_2024-04-14-10-32-23-86_6fbed06f4d8fcb7cc11bfd5e60f8cca0](https://github.com/slowmist/Knowledge-Base/assets/166977640/60372ff5-4571-4bbb-9c8b-0f454d5f67c8)

**Comment by William23743** [comment]
why can't my sender application wallet connect to the sender browser

My Twitter name is @william23743
![Uploading Screenshot_2024-04-14-10-32-23-86_6fbed06f4d8fcb7cc11bfd5e60f8cca0.png…]()

**Comment by William23743** [comment]
![Screenshot_2024-04-14-11-28-33-08_0b2fce7a16bf2b728d6ffa28c8d60efb](https://github.com/slowmist/Knowledge-Base/assets/166977640/566c4531-eb0a-469a-b6af-4db590c380da)

**Comment by William23743** [comment]
why did my airdrop disappear, even though yesterday I activated my airdrop and got lots of points and referrals
please help me,i have tried very hard for senderlabs
![Uploading Screenshot_2024-04-14-21-03-36-87_6fbed06f4d8fcb7cc11bfd5e60f8cca0.png…]()

**Comment by William23743** [comment]
![Screenshot_2024-04-14-21-11-22-64_0b2fce7a16bf2b728d6ffa28c8d60efb](https://github.com/slowmist/Knowledge-Base/assets/166977640/4839aa12-ae0e-401a-8736-3c5527e478ca)

**Comment by William23743** [comment]
![Uploading Screenshot_2024-04-14-21-04-36-49_6fbed06f4d8fcb7cc11bfd5e60f8cca0.png…]()

**Comment by William23743** [comment]
![Screenshot_2024-04-14-21-03-36-87_6fbed06f4d8fcb7cc11bfd5e60f8cca0](https://github.com/slowmist/Knowledge-Base/assets/166977640/5908f128-c65c-4b28-b4eb-345a92b3f03c)
