### ISSUE TITLE
My Balance on sender wallet is gone , its automaticaly send to unknown address

### ISSUE THREAD

**Issue by rzkvrsh** [slowmist/Knowledge-Base#27]
My Balance on sender wallet is gone , its automaticaly send to unknown address.

how can it be , 
Im never shared my pharse or another security code . 
But I lost my funding . 
Please help me

**Comment by crypto-Beta** [comment]
My Balance on sender wallet is gone , its automaticaly send to unknown address.

how can it be ,
Im never shared my pharse or another security code .
But I lost my funding .
Please help me

**Comment by Arasham00** [comment]
کمک می خواهید
